# == Code by 21 rats#2113 | Worms by verenacafern#8203 == #
# Free to use, provided all derivatives are free & open source
# Appreciated but not required if you show me what you're using my code for owo


# == What The Heck is This? == #
# Right now? Not much. Soon it will link in with discord, and use the images
# pregenerated by wormgenerator.py to do cool things!


# === Imports === #

import os
import random
import discord
from dotenv import load_dotenv

load_dotenv()
TOKEN = os.getenv('DISCORD_TOKEN')
GUILD = os.getenv('DISCORD_GUILD')

client = discord.Client()


@client.event
async def on_ready():
    for guild in client.guilds:
        if guild.name == GUILD:
            break

    print(
        f'[INFO] {client.user} is connected to the following guild:\n'
        f'[INFO] {guild.name}(id: {guild.id})'
    )

    members = '\n - '.join([member.name for member in guild.members])
    print(f'[INFO] Guild Members:\n - {members}')


@client.event
async def on_member_join(member):
    await member.create_dm()
    await member.dm_channel.send(
        f'Hi {member.name}, welcome to my Discord server!'
    )


@client.event
async def on_message(message):
    if message.author == client.user:
        return

    random_messages = [
        'I declare you 99% valid.',
        'Do you ever just...scream into the void',
    ]

    if message.content == '$ test':
        response = random.choice(random_messages)
        await message.channel.send(response)


client.run(TOKEN)
